### ISSUE TITLE
[bug] database casts pickup_point_id to int and loses the prefix 0 from some pickup point ids

### ISSUE THREAD

**Issue by jukkakorpelainen** [Pakettikauppa/prestashop-pakettikauppa#3]
Database now casts for example pickup point id "011503200" to int 11503200 and it fails to match the selected one at least on Prestashop side.
https://github.com/Pakettikauppa/prestashop-pakettikauppa/blob/da19545cff15c51018e69f71c0a1b6f518e50e3e/sql/install.php#L32
Changing it to varchar(20) or something should fix the issue very easily. Should probably also check is_numeric() before saving to db to prevent attacks if gonna change to prevent xss attacks.
Another option is to cast all ids to ints before checking matching values if Posti isn't so picky with these prefix zeroes. But more work prob.

**Comment by joosev** [comment]
Fixed
